window.IIDX_SCENE_MANIFEST = {
  "canvas": {
    "width": 1920,
    "height": 1080
  },
  "fonts": [
    {
      "family": "FZCCHJW",
      "src": "assets/fonts/FZCCHJW.TTF"
    }
  ],
  "templates": {
    "dp_arena": {
      "layers": [
        {
          "kind": "image",
          "id": "image_background_color_0",
          "src": "assets/layers/dp_arena/000_image_background_color_0.png",
          "x": -5.0,
          "y": -5.0,
          "width": 1932,
          "height": 1090
        },
        {
          "kind": "image",
          "id": "image_header_layer_1",
          "src": "assets/layers/dp_arena/001_image_header_layer_1.png",
          "x": 0.0,
          "y": 0.0,
          "width": 1518,
          "height": 71
        },
        {
          "kind": "text",
          "id": "header_brand",
          "default": "TPL S3",
          "x": 10.0,
          "y": 10.0,
          "width": 173.0,
          "height": 35.0,
          "fontSize": 45.881,
          "fontFamily": "FZCCHJW",
          "fontFallback": "Arial",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "text",
          "id": "header_match_type",
          "default": "DP个人赛",
          "x": 226.0,
          "y": 8.0,
          "width": 161.0,
          "height": 36.0,
          "fontSize": 36.349,
          "fontFamily": "FZCCHJW",
          "fontFallback": "Arial",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "text",
          "id": "header_round",
          "default": "ROUND 1",
          "x": 1135.0,
          "y": 16.0,
          "width": 157.0,
          "height": 25.0,
          "fontSize": 32.532,
          "fontFamily": "FZCCHJW",
          "fontFallback": "Arial",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "text",
          "id": "header_theme",
          "default": "SCRATCH",
          "x": 1330.0,
          "y": 15.0,
          "width": 172.0,
          "height": 25.0,
          "fontSize": 32.532,
          "fontFamily": "FZCCHJW",
          "fontFallback": "Arial",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "image",
          "id": "image_bpm_6",
          "src": "assets/layers/dp_arena/006_image_bpm_6.png",
          "x": 662.0,
          "y": 83.0,
          "width": 210,
          "height": 33
        },
        {
          "kind": "image",
          "id": "image_dp_7",
          "src": "assets/layers/dp_arena/007_image_dp_7.png",
          "x": 549.0,
          "y": 0.0,
          "width": 436,
          "height": 83
        },
        {
          "kind": "image",
          "id": "image_1_1_judge_8",
          "src": "assets/layers/dp_arena/008_image_1_1_judge_8.png",
          "x": 356.0,
          "y": 484.0,
          "width": 216,
          "height": 103
        },
        {
          "kind": "image",
          "id": "image_1_1_9",
          "src": "assets/layers/dp_arena/009_image_1_1_9.png",
          "x": 11.0,
          "y": 486.0,
          "width": 345,
          "height": 101
        },
        {
          "kind": "image",
          "id": "image_1_layer_10",
          "src": "assets/layers/dp_arena/010_image_1_layer_10.png",
          "x": 13.0,
          "y": 112.0,
          "width": 561,
          "height": 374
        },
        {
          "kind": "image",
          "id": "image_1_red_name_board_11",
          "src": "assets/layers/dp_arena/011_image_1_red_name_board_11.png",
          "x": 13.0,
          "y": 112.0,
          "width": 295,
          "height": 51,
          "hueKey": "image_1_red_name_board_11"
        },
        {
          "kind": "text",
          "id": "machine_1_player",
          "default": "duiyuan",
          "x": 54.0,
          "y": 123.0,
          "width": 193.0,
          "height": 46.0,
          "fontSize": 38.692,
          "fontFamily": "FZLTTHJW",
          "fontFallback": "FZCCHJW",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0888,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "image",
          "id": "image_2_2_judge_13",
          "src": "assets/layers/dp_arena/013_image_2_2_judge_13.png",
          "x": 1307.0,
          "y": 484.0,
          "width": 216,
          "height": 103
        },
        {
          "kind": "image",
          "id": "image_2_2_14",
          "src": "assets/layers/dp_arena/014_image_2_2_14.png",
          "x": 962.0,
          "y": 486.0,
          "width": 345,
          "height": 101
        },
        {
          "kind": "image",
          "id": "image_2_layer_15",
          "src": "assets/layers/dp_arena/015_image_2_layer_15.png",
          "x": 962.0,
          "y": 112.0,
          "width": 560,
          "height": 374
        },
        {
          "kind": "image",
          "id": "image_2_red_name_board_16",
          "src": "assets/layers/dp_arena/016_image_2_red_name_board_16.png",
          "x": 1221.0,
          "y": 112.0,
          "width": 295,
          "height": 51,
          "hueKey": "image_2_red_name_board_16"
        },
        {
          "kind": "text",
          "id": "machine_2_player",
          "default": "duiyuan",
          "x": 1284.0,
          "y": 123.0,
          "width": 194.0,
          "height": 46.0,
          "fontSize": 38.692,
          "fontFamily": "FZLTTHJW",
          "fontFallback": "FZCCHJW",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0888,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "image",
          "id": "image_3_3_judge_18",
          "src": "assets/layers/dp_arena/018_image_3_3_judge_18.png",
          "x": 356.0,
          "y": 968.0,
          "width": 216,
          "height": 103
        },
        {
          "kind": "image",
          "id": "image_3_3_19",
          "src": "assets/layers/dp_arena/019_image_3_3_19.png",
          "x": 11.0,
          "y": 970.0,
          "width": 345,
          "height": 101
        },
        {
          "kind": "image",
          "id": "image_3_3_20",
          "src": "assets/layers/dp_arena/020_image_3_3_20.png",
          "x": 13.0,
          "y": 596.0,
          "width": 561,
          "height": 374
        },
        {
          "kind": "image",
          "id": "image_3_red_name_board_21",
          "src": "assets/layers/dp_arena/021_image_3_red_name_board_21.png",
          "x": 14.0,
          "y": 595.0,
          "width": 295,
          "height": 51,
          "hueKey": "image_3_red_name_board_21"
        },
        {
          "kind": "text",
          "id": "machine_3_player",
          "default": "duiyuan",
          "x": 55.0,
          "y": 606.0,
          "width": 193.0,
          "height": 46.0,
          "fontSize": 38.692,
          "fontFamily": "FZLTTHJW",
          "fontFallback": "FZCCHJW",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0888,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "image",
          "id": "image_4_4_judge_23",
          "src": "assets/layers/dp_arena/023_image_4_4_judge_23.png",
          "x": 1307.0,
          "y": 968.0,
          "width": 216,
          "height": 103
        },
        {
          "kind": "image",
          "id": "image_4_4_24",
          "src": "assets/layers/dp_arena/024_image_4_4_24.png",
          "x": 962.0,
          "y": 970.0,
          "width": 345,
          "height": 101
        },
        {
          "kind": "image",
          "id": "image_4_4_25",
          "src": "assets/layers/dp_arena/025_image_4_4_25.png",
          "x": 962.0,
          "y": 596.0,
          "width": 560,
          "height": 374
        },
        {
          "kind": "image",
          "id": "image_4_red_name_board_26",
          "src": "assets/layers/dp_arena/026_image_4_red_name_board_26.png",
          "x": 1222.0,
          "y": 595.0,
          "width": 295,
          "height": 51,
          "hueKey": "image_4_red_name_board_26"
        },
        {
          "kind": "text",
          "id": "machine_4_player",
          "default": "duiyuan",
          "x": 1284.0,
          "y": 606.0,
          "width": 194.0,
          "height": 46.0,
          "fontSize": 38.692,
          "fontFamily": "FZLTTHJW",
          "fontFallback": "FZCCHJW",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0888,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "image",
          "id": "image_layer_28",
          "src": "assets/layers/dp_arena/028_image_layer_28.png",
          "x": 584.0,
          "y": 128.0,
          "width": 366,
          "height": 938
        },
        {
          "kind": "image",
          "id": "image_chat_live_layer_29",
          "src": "assets/layers/dp_arena/029_image_chat_live_layer_29.png",
          "x": 1526.0,
          "y": 848.0,
          "width": 387,
          "height": 219
        },
        {
          "kind": "image",
          "id": "image_chat_live_layer_30",
          "src": "assets/layers/dp_arena/030_image_chat_live_layer_30.png",
          "x": 1529.0,
          "y": 112.0,
          "width": 383,
          "height": 728
        },
        {
          "kind": "image",
          "id": "image_chat_live_layer_31",
          "src": "assets/layers/dp_arena/031_image_chat_live_layer_31.png",
          "x": 1539.0,
          "y": 159.0,
          "width": 364,
          "height": 670
        },
        {
          "kind": "image",
          "id": "image_chat_live_layer_32",
          "src": "assets/layers/dp_arena/032_image_chat_live_layer_32.png",
          "x": 1696.0,
          "y": 147.0,
          "width": 234,
          "height": 232
        },
        {
          "kind": "image",
          "id": "image_chat_live_layer_33",
          "src": "assets/layers/dp_arena/033_image_chat_live_layer_33.png",
          "x": 1516.0,
          "y": 613.0,
          "width": 201,
          "height": 245
        },
        {
          "kind": "text",
          "id": "chat_title",
          "default": "CHAT",
          "x": 1542.0,
          "y": 120.0,
          "width": 121.0,
          "height": 31.0,
          "fontSize": 39.576,
          "fontFamily": "FZCCHJW",
          "fontFallback": "Arial",
          "fontWeight": 400,
          "color": "#ffeeff",
          "horizontalScale": 1.0,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "image",
          "id": "image_advertisement_tpls3_logo_35",
          "src": "assets/layers/dp_arena/035_image_advertisement_tpls3_logo_35.png",
          "x": 1523.0,
          "y": 16.0,
          "width": 149,
          "height": 82
        },
        {
          "kind": "image",
          "id": "image_advertisement_33logo_36",
          "src": "assets/layers/dp_arena/036_image_advertisement_33logo_36.png",
          "x": 1691.0,
          "y": 23.0,
          "width": 221,
          "height": 64
        }
      ]
    },
    "dp_bpl": {
      "layers": [
        {
          "kind": "image",
          "id": "image_background_color_0",
          "src": "assets/layers/dp_bpl/000_image_background_color_0.png",
          "x": 0.0,
          "y": 0.0,
          "width": 1920,
          "height": 1080
        },
        {
          "kind": "image",
          "id": "image_header_layer_1",
          "src": "assets/layers/dp_bpl/001_image_header_layer_1.png",
          "x": 226.56,
          "y": -0.48,
          "width": 1471,
          "height": 90
        },
        {
          "kind": "text",
          "id": "header_brand",
          "default": "TPL S3",
          "x": 239.52,
          "y": 13.92,
          "width": 218.4,
          "height": 43.68,
          "fontSize": 13.941,
          "fontFamily": "FZCCHJW",
          "fontFallback": "Arial",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "text",
          "id": "header_match_type",
          "default": "DP团队赛",
          "x": 511.68,
          "y": 11.76,
          "width": 203.28,
          "height": 45.12,
          "fontSize": 11.045,
          "fontFamily": "FZCCHJW",
          "fontFallback": "Arial",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "text",
          "id": "header_round",
          "default": "ROUND 1",
          "x": 1213.68,
          "y": 20.4,
          "width": 197.52,
          "height": 31.2,
          "fontSize": 9.885,
          "fontFamily": "FZCCHJW",
          "fontFallback": "Arial",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "text",
          "id": "header_theme",
          "default": "SCRATCH",
          "x": 1460.16,
          "y": 19.92,
          "width": 217.68,
          "height": 31.2,
          "fontSize": 9.885,
          "fontFamily": "FZCCHJW",
          "fontFallback": "Arial",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "image",
          "id": "image_bpm_6",
          "src": "assets/layers/dp_bpl/006_image_bpm_6.png",
          "x": 878.4,
          "y": 77.04,
          "width": 163,
          "height": 36
        },
        {
          "kind": "image",
          "id": "image_dp_7",
          "src": "assets/layers/dp_bpl/007_image_dp_7.png",
          "x": 741.84,
          "y": 0.0,
          "width": 436,
          "height": 83
        },
        {
          "kind": "image",
          "id": "image_layer_8",
          "src": "assets/layers/dp_bpl/008_image_layer_8.png",
          "x": 800.4,
          "y": 120.0,
          "width": 321,
          "height": 759
        },
        {
          "kind": "image",
          "id": "image_left_layer_9",
          "src": "assets/layers/dp_bpl/009_image_left_layer_9.png",
          "x": 1.68,
          "y": 885.12,
          "width": 652,
          "height": 192
        },
        {
          "kind": "image",
          "id": "image_left_layer_10",
          "src": "assets/layers/dp_bpl/010_image_left_layer_10.png",
          "x": 0.0,
          "y": 200.64,
          "width": 799,
          "height": 678
        },
        {
          "kind": "image",
          "id": "image_left_judge_11",
          "src": "assets/layers/dp_bpl/011_image_left_judge_11.png",
          "x": 518.4,
          "y": 735.12,
          "width": 280,
          "height": 143
        },
        {
          "kind": "image",
          "id": "image_left_left_team_name_red_board_long_12",
          "src": "assets/layers/dp_bpl/012_image_left_left_team_name_red_board_long_12.png",
          "x": 506.16,
          "y": 148.8,
          "width": 221,
          "height": 46,
          "hueKey": "image_left_left_team_name_red_board_long_12"
        },
        {
          "kind": "text",
          "id": "left_team_name",
          "default": "左边队名",
          "x": 565.2,
          "y": 159.12,
          "width": 141.12,
          "height": 34.8,
          "fontSize": 8.71,
          "fontFamily": "FZLTTHJW",
          "fontFallback": "FZCCHJW",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "image",
          "id": "image_left_left_score_red_board_14",
          "src": "assets/layers/dp_bpl/014_image_left_left_score_red_board_14.png",
          "x": 541.44,
          "y": 99.12,
          "width": 185,
          "height": 46,
          "hueKey": "image_left_left_score_red_board_14"
        },
        {
          "kind": "text",
          "id": "left_points",
          "default": "29PT",
          "x": 608.88,
          "y": 107.04,
          "width": 80.4,
          "height": 32.64,
          "fontSize": 8.71,
          "fontFamily": "FZLTTHJW",
          "fontFallback": "FZCCHJW",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "image",
          "id": "image_left_left_player_red_name_board_16",
          "src": "assets/layers/dp_bpl/016_image_left_left_player_red_name_board_16.png",
          "x": 127.44,
          "y": 121.44,
          "width": 423,
          "height": 73,
          "hueKey": "image_left_left_player_red_name_board_16"
        },
        {
          "kind": "text",
          "id": "left_player",
          "default": "duiyuan",
          "x": 187.2,
          "y": 138.24,
          "width": 276.48,
          "height": 65.52,
          "fontSize": 13.364,
          "fontFamily": "FZLTTHJW",
          "fontFallback": "FZCCHJW",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0888,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "image",
          "id": "image_right_layer_18",
          "src": "assets/layers/dp_bpl/018_image_right_layer_18.png",
          "x": 1267.68,
          "y": 885.12,
          "width": 652,
          "height": 192
        },
        {
          "kind": "image",
          "id": "image_right_layer_19",
          "src": "assets/layers/dp_bpl/019_image_right_layer_19.png",
          "x": 1121.28,
          "y": 200.88,
          "width": 799,
          "height": 678
        },
        {
          "kind": "image",
          "id": "image_right_judge_20",
          "src": "assets/layers/dp_bpl/020_image_right_judge_20.png",
          "x": 1120.8,
          "y": 735.12,
          "width": 280,
          "height": 143
        },
        {
          "kind": "image",
          "id": "image_right_right_team_name_red_board_long_21",
          "src": "assets/layers/dp_bpl/021_image_right_right_team_name_red_board_long_21.png",
          "x": 1205.28,
          "y": 148.8,
          "width": 221,
          "height": 46,
          "hueKey": "image_right_right_team_name_red_board_long_21"
        },
        {
          "kind": "text",
          "id": "right_team_name",
          "default": "右边队名",
          "x": 1231.2,
          "y": 159.12,
          "width": 140.88,
          "height": 34.8,
          "fontSize": 8.71,
          "fontFamily": "FZLTTHJW",
          "fontFallback": "FZCCHJW",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "image",
          "id": "image_right_right_score_red_board_23",
          "src": "assets/layers/dp_bpl/023_image_right_right_score_red_board_23.png",
          "x": 1205.28,
          "y": 99.12,
          "width": 185,
          "height": 46,
          "hueKey": "image_right_right_score_red_board_23"
        },
        {
          "kind": "text",
          "id": "right_points",
          "default": "30PT",
          "x": 1243.68,
          "y": 107.04,
          "width": 81.84,
          "height": 32.64,
          "fontSize": 8.71,
          "fontFamily": "FZLTTHJW",
          "fontFallback": "FZCCHJW",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "image",
          "id": "image_right_right_player_red_name_board_25",
          "src": "assets/layers/dp_bpl/025_image_right_right_player_red_name_board_25.png",
          "x": 1378.32,
          "y": 121.2,
          "width": 426,
          "height": 73,
          "hueKey": "image_right_right_player_red_name_board_25"
        },
        {
          "kind": "text",
          "id": "right_player",
          "default": "duiyuan",
          "x": 1467.84,
          "y": 138.0,
          "width": 278.16,
          "height": 65.76,
          "fontSize": 13.448,
          "fontFamily": "FZLTTHJW",
          "fontFallback": "FZCCHJW",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0888,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "image",
          "id": "image_chat_live_layer_27",
          "src": "assets/layers/dp_bpl/027_image_chat_live_layer_27.png",
          "x": 656.88,
          "y": 885.6,
          "width": 336,
          "height": 189
        },
        {
          "kind": "image",
          "id": "image_chat_live_layer_28",
          "src": "assets/layers/dp_bpl/028_image_chat_live_layer_28.png",
          "x": 996.48,
          "y": 885.36,
          "width": 268,
          "height": 189
        },
        {
          "kind": "image",
          "id": "image_chat_live_layer_29",
          "src": "assets/layers/dp_bpl/029_image_chat_live_layer_29.png",
          "x": 1030.32,
          "y": 890.64,
          "width": 229,
          "height": 179
        },
        {
          "kind": "image",
          "id": "image_chat_live_layer_30",
          "src": "assets/layers/dp_bpl/030_image_chat_live_layer_30.png",
          "x": 1012.08,
          "y": 954.72,
          "width": 106,
          "height": 125
        },
        {
          "kind": "image",
          "id": "image_chat_live_layer_31",
          "src": "assets/layers/dp_bpl/031_image_chat_live_layer_31.png",
          "x": 1151.28,
          "y": 879.36,
          "width": 122,
          "height": 122
        },
        {
          "kind": "text",
          "id": "chat_title",
          "default": "CHAT",
          "x": 1001.28,
          "y": 891.6,
          "width": 22.56,
          "height": 91.68,
          "fontSize": 7.181,
          "fontFamily": "FZCCHJW",
          "fontFallback": "Arial",
          "fontWeight": 400,
          "color": "#ffeeff",
          "horizontalScale": 1.0,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "image",
          "id": "image_advertisement_tpls3logo_33",
          "src": "assets/layers/dp_bpl/033_image_advertisement_tpls3logo_33.png",
          "x": 22.56,
          "y": 10.08,
          "width": 171,
          "height": 95
        },
        {
          "kind": "image",
          "id": "image_advertisement_33logo_34",
          "src": "assets/layers/dp_bpl/034_image_advertisement_33logo_34.png",
          "x": 1714.08,
          "y": 22.32,
          "width": 195,
          "height": 56
        }
      ]
    },
    "sp_arena": {
      "layers": [
        {
          "kind": "image",
          "id": "image_background_board_0",
          "src": "assets/layers/sp_arena/000_image_background_board_0.png",
          "x": 0.0,
          "y": 0.0,
          "width": 1920,
          "height": 1080
        },
        {
          "kind": "image",
          "id": "image_header_113_112_111_1",
          "src": "assets/layers/sp_arena/001_image_header_113_112_111_1.png",
          "x": 0.0,
          "y": 0.0,
          "width": 1920,
          "height": 90
        },
        {
          "kind": "text",
          "id": "header_brand",
          "default": "TPL S3",
          "x": 13.43,
          "y": 13.44,
          "width": 218.236,
          "height": 43.68,
          "fontSize": 13.941,
          "fontFamily": "FZCCHJW",
          "fontFallback": "Arial",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "text",
          "id": "header_match_type",
          "default": "SP个人赛",
          "x": 284.187,
          "y": 11.28,
          "width": 201.689,
          "height": 45.12,
          "fontSize": 11.045,
          "fontFamily": "FZCCHJW",
          "fontFallback": "Arial",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "text",
          "id": "header_round",
          "default": "ROUND 1",
          "x": 1436.043,
          "y": 19.92,
          "width": 197.372,
          "height": 31.2,
          "fontSize": 9.885,
          "fontFamily": "FZCCHJW",
          "fontFallback": "Arial",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "text",
          "id": "header_theme",
          "default": "SCRATCH",
          "x": 1682.338,
          "y": 19.44,
          "width": 217.517,
          "height": 31.2,
          "fontSize": 9.885,
          "fontFamily": "FZCCHJW",
          "fontFallback": "Arial",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "image",
          "id": "image_bpm_6",
          "src": "assets/layers/sp_arena/006_image_bpm_6.png",
          "x": 828.099,
          "y": 83.04,
          "width": 253,
          "height": 40
        },
        {
          "kind": "image",
          "id": "image_sp_7",
          "src": "assets/layers/sp_arena/007_image_sp_7.png",
          "x": 521.849,
          "y": 0.0,
          "width": 872,
          "height": 86
        },
        {
          "kind": "image",
          "id": "image_1_1_judge_8",
          "src": "assets/layers/sp_arena/008_image_1_1_judge_8.png",
          "x": 11.032,
          "y": 888.72,
          "width": 374,
          "height": 191
        },
        {
          "kind": "image",
          "id": "image_1_1_9",
          "src": "assets/layers/sp_arena/009_image_1_1_9.png",
          "x": 10.792,
          "y": 650.4,
          "width": 375,
          "height": 238
        },
        {
          "kind": "image",
          "id": "image_1_1_10",
          "src": "assets/layers/sp_arena/010_image_1_1_10.png",
          "x": 10.792,
          "y": 136.8,
          "width": 375,
          "height": 517
        },
        {
          "kind": "image",
          "id": "image_1_red_name_board_11",
          "src": "assets/layers/sp_arena/011_image_1_red_name_board_11.png",
          "x": 21.104,
          "y": 111.84,
          "width": 322,
          "height": 56,
          "hueKey": "image_1_red_name_board_11"
        },
        {
          "kind": "text",
          "id": "machine_1_player",
          "default": "duiyuan",
          "x": 65.951,
          "y": 124.56,
          "width": 209.843,
          "height": 49.92,
          "fontSize": 10.154,
          "fontFamily": "FZLTTHJW",
          "fontFallback": "FZCCHJW",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0888,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "image",
          "id": "image_2_2_judge_13",
          "src": "assets/layers/sp_arena/013_image_2_2_judge_13.png",
          "x": 391.626,
          "y": 888.72,
          "width": 374,
          "height": 191
        },
        {
          "kind": "image",
          "id": "image_2_2_14",
          "src": "assets/layers/sp_arena/014_image_2_2_14.png",
          "x": 391.626,
          "y": 650.4,
          "width": 375,
          "height": 238
        },
        {
          "kind": "image",
          "id": "image_2_2_15",
          "src": "assets/layers/sp_arena/015_image_2_2_15.png",
          "x": 391.626,
          "y": 137.04,
          "width": 374,
          "height": 517
        },
        {
          "kind": "image",
          "id": "image_2_red_name_board_16",
          "src": "assets/layers/sp_arena/016_image_2_red_name_board_16.png",
          "x": 397.622,
          "y": 113.04,
          "width": 322,
          "height": 56,
          "hueKey": "image_2_red_name_board_16"
        },
        {
          "kind": "text",
          "id": "machine_2_player",
          "default": "duiyuan",
          "x": 443.188,
          "y": 125.52,
          "width": 209.843,
          "height": 49.92,
          "fontSize": 10.154,
          "fontFamily": "FZLTTHJW",
          "fontFallback": "FZCCHJW",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0888,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "image",
          "id": "image_3_3_judge_18",
          "src": "assets/layers/sp_arena/018_image_3_3_judge_18.png",
          "x": 1153.775,
          "y": 888.72,
          "width": 374,
          "height": 191
        },
        {
          "kind": "image",
          "id": "image_3_3_19",
          "src": "assets/layers/sp_arena/019_image_3_3_19.png",
          "x": 1153.535,
          "y": 650.4,
          "width": 375,
          "height": 238
        },
        {
          "kind": "image",
          "id": "image_3_3_20",
          "src": "assets/layers/sp_arena/020_image_3_3_20.png",
          "x": 1153.775,
          "y": 137.04,
          "width": 374,
          "height": 517
        },
        {
          "kind": "image",
          "id": "image_3_red_name_board_21",
          "src": "assets/layers/sp_arena/021_image_3_red_name_board_21.png",
          "x": 1150.897,
          "y": 113.04,
          "width": 322,
          "height": 56,
          "hueKey": "image_3_red_name_board_21"
        },
        {
          "kind": "text",
          "id": "machine_3_player",
          "default": "duiyuan",
          "x": 1196.223,
          "y": 125.52,
          "width": 209.843,
          "height": 49.92,
          "fontSize": 10.154,
          "fontFamily": "FZLTTHJW",
          "fontFallback": "FZCCHJW",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0888,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "image",
          "id": "image_4_4_judge_23",
          "src": "assets/layers/sp_arena/023_image_4_4_judge_23.png",
          "x": 1535.808,
          "y": 888.72,
          "width": 374,
          "height": 191
        },
        {
          "kind": "image",
          "id": "image_4_4_24",
          "src": "assets/layers/sp_arena/024_image_4_4_24.png",
          "x": 1535.568,
          "y": 650.4,
          "width": 375,
          "height": 238
        },
        {
          "kind": "image",
          "id": "image_4_4_25",
          "src": "assets/layers/sp_arena/025_image_4_4_25.png",
          "x": 1535.808,
          "y": 137.04,
          "width": 374,
          "height": 517
        },
        {
          "kind": "image",
          "id": "image_4_red_name_board_26",
          "src": "assets/layers/sp_arena/026_image_4_red_name_board_26.png",
          "x": 1531.252,
          "y": 111.84,
          "width": 322,
          "height": 56,
          "hueKey": "image_4_red_name_board_26"
        },
        {
          "kind": "text",
          "id": "machine_4_player",
          "default": "duiyuan",
          "x": 1576.578,
          "y": 124.56,
          "width": 209.843,
          "height": 49.92,
          "fontSize": 10.154,
          "fontFamily": "FZLTTHJW",
          "fontFallback": "FZCCHJW",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0888,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "image",
          "id": "image_layer_28",
          "src": "assets/layers/sp_arena/028_image_layer_28.png",
          "x": 776.298,
          "y": 136.08,
          "width": 368,
          "height": 946
        }
      ]
    },
    "sp_bpl": {
      "layers": [
        {
          "kind": "image",
          "id": "image_background_color_0",
          "src": "assets/layers/sp_bpl/000_image_background_color_0.png",
          "x": 0.0,
          "y": 0.0,
          "width": 1920,
          "height": 1080
        },
        {
          "kind": "image",
          "id": "image_header_layer_1",
          "src": "assets/layers/sp_bpl/001_image_header_layer_1.png",
          "x": 0.0,
          "y": 0.0,
          "width": 1399,
          "height": 66
        },
        {
          "kind": "text",
          "id": "header_brand",
          "default": "TPL S3",
          "x": 9.36,
          "y": 9.84,
          "width": 158.88,
          "height": 31.92,
          "fontSize": 10.155,
          "fontFamily": "FZCCHJW",
          "fontFallback": "Arial",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "text",
          "id": "header_match_type",
          "default": "SP团队赛",
          "x": 206.4,
          "y": 8.16,
          "width": 147.12,
          "height": 32.88,
          "fontSize": 8.045,
          "fontFamily": "FZCCHJW",
          "fontFallback": "Arial",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "text",
          "id": "header_round",
          "default": "ROUND 1",
          "x": 1045.68,
          "y": 14.4,
          "width": 144.0,
          "height": 22.8,
          "fontSize": 7.2,
          "fontFamily": "FZCCHJW",
          "fontFallback": "Arial",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "text",
          "id": "header_theme",
          "default": "SCRATCH",
          "x": 1225.2,
          "y": 13.92,
          "width": 158.64,
          "height": 22.8,
          "fontSize": 7.2,
          "fontFamily": "FZCCHJW",
          "fontFallback": "Arial",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "image",
          "id": "image_bpm_6",
          "src": "assets/layers/sp_bpl/006_image_bpm_6.png",
          "x": 618.96,
          "y": 62.16,
          "width": 166,
          "height": 26
        },
        {
          "kind": "image",
          "id": "image_sp_7",
          "src": "assets/layers/sp_bpl/007_image_sp_7.png",
          "x": 379.68,
          "y": 0.0,
          "width": 635,
          "height": 62
        },
        {
          "kind": "image",
          "id": "image_layer_8",
          "src": "assets/layers/sp_bpl/008_image_layer_8.png",
          "x": 528.0,
          "y": 86.64,
          "width": 348,
          "height": 822
        },
        {
          "kind": "image",
          "id": "image_left_layer_9",
          "src": "assets/layers/sp_bpl/009_image_left_layer_9.png",
          "x": 29.52,
          "y": 901.2,
          "width": 284,
          "height": 179
        },
        {
          "kind": "image",
          "id": "image_left_judge_10",
          "src": "assets/layers/sp_bpl/010_image_left_judge_10.png",
          "x": 313.2,
          "y": 912.72,
          "width": 328,
          "height": 167
        },
        {
          "kind": "image",
          "id": "image_left_layer_11",
          "src": "assets/layers/sp_bpl/011_image_left_layer_11.png",
          "x": 29.52,
          "y": 114.72,
          "width": 480,
          "height": 793
        },
        {
          "kind": "image",
          "id": "image_left_left_team_name_red_board_long_12",
          "src": "assets/layers/sp_bpl/012_image_left_left_team_name_red_board_long_12.png",
          "x": 332.4,
          "y": 108.24,
          "width": 177,
          "height": 37,
          "hueKey": "image_left_left_team_name_red_board_long_12"
        },
        {
          "kind": "text",
          "id": "left_team_name",
          "default": "左边队名",
          "x": 380.16,
          "y": 116.88,
          "width": 113.04,
          "height": 27.84,
          "fontSize": 6.982,
          "fontFamily": "FZLTTHJW",
          "fontFallback": "FZCCHJW",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "image",
          "id": "image_left_left_score_red_board_14",
          "src": "assets/layers/sp_bpl/014_image_left_left_score_red_board_14.png",
          "x": 360.72,
          "y": 68.64,
          "width": 149,
          "height": 37,
          "hueKey": "image_left_left_score_red_board_14"
        },
        {
          "kind": "text",
          "id": "left_points",
          "default": "29PT",
          "x": 415.2,
          "y": 75.12,
          "width": 64.32,
          "height": 26.16,
          "fontSize": 6.982,
          "fontFamily": "FZLTTHJW",
          "fontFallback": "FZCCHJW",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "image",
          "id": "image_left_left_player_red_name_board_16",
          "src": "assets/layers/sp_bpl/016_image_left_left_player_red_name_board_16.png",
          "x": 29.04,
          "y": 86.4,
          "width": 340,
          "height": 59,
          "hueKey": "image_left_left_player_red_name_board_16"
        },
        {
          "kind": "text",
          "id": "left_player",
          "default": "duiyuan",
          "x": 77.04,
          "y": 99.84,
          "width": 221.76,
          "height": 52.56,
          "fontSize": 10.713,
          "fontFamily": "FZLTTHJW",
          "fontFallback": "FZCCHJW",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0888,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "image",
          "id": "image_right_layer_18",
          "src": "assets/layers/sp_bpl/018_image_right_layer_18.png",
          "x": 1089.6,
          "y": 902.64,
          "width": 283,
          "height": 177
        },
        {
          "kind": "image",
          "id": "image_right_judge_19",
          "src": "assets/layers/sp_bpl/019_image_right_judge_19.png",
          "x": 741.36,
          "y": 912.72,
          "width": 328,
          "height": 167
        },
        {
          "kind": "image",
          "id": "image_right_layer_20",
          "src": "assets/layers/sp_bpl/020_image_right_layer_20.png",
          "x": 893.28,
          "y": 114.72,
          "width": 480,
          "height": 793
        },
        {
          "kind": "image",
          "id": "image_right_right_team_name_red_board_long_21",
          "src": "assets/layers/sp_bpl/021_image_right_right_team_name_red_board_long_21.png",
          "x": 892.8,
          "y": 108.24,
          "width": 177,
          "height": 37,
          "hueKey": "image_right_right_team_name_red_board_long_21"
        },
        {
          "kind": "text",
          "id": "right_team_name",
          "default": "右边队名",
          "x": 913.68,
          "y": 116.88,
          "width": 113.28,
          "height": 27.84,
          "fontSize": 6.982,
          "fontFamily": "FZLTTHJW",
          "fontFallback": "FZCCHJW",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "image",
          "id": "image_right_right_score_red_board_23",
          "src": "assets/layers/sp_bpl/023_image_right_right_score_red_board_23.png",
          "x": 893.04,
          "y": 68.64,
          "width": 149,
          "height": 37,
          "hueKey": "image_right_right_score_red_board_23"
        },
        {
          "kind": "text",
          "id": "right_points",
          "default": "30PT",
          "x": 924.0,
          "y": 75.12,
          "width": 65.28,
          "height": 26.16,
          "fontSize": 6.982,
          "fontFamily": "FZLTTHJW",
          "fontFallback": "FZCCHJW",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "image",
          "id": "image_right_right_player_red_name_board_25",
          "src": "assets/layers/sp_bpl/025_image_right_right_player_red_name_board_25.png",
          "x": 1031.76,
          "y": 86.16,
          "width": 342,
          "height": 59,
          "hueKey": "image_right_right_player_red_name_board_25"
        },
        {
          "kind": "text",
          "id": "right_player",
          "default": "duiyuan",
          "x": 1103.52,
          "y": 99.84,
          "width": 223.44,
          "height": 52.8,
          "fontSize": 10.781,
          "fontFamily": "FZLTTHJW",
          "fontFallback": "FZCCHJW",
          "fontWeight": 400,
          "color": "#ffffff",
          "horizontalScale": 1.0888,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "image",
          "id": "image_chat_live_layer_27",
          "src": "assets/layers/sp_bpl/027_image_chat_live_layer_27.png",
          "x": 1413.36,
          "y": 790.08,
          "width": 487,
          "height": 274
        },
        {
          "kind": "image",
          "id": "image_chat_live_layer_28",
          "src": "assets/layers/sp_bpl/028_image_chat_live_layer_28.png",
          "x": 1413.36,
          "y": 152.16,
          "width": 487,
          "height": 619
        },
        {
          "kind": "image",
          "id": "image_chat_live_layer_29",
          "src": "assets/layers/sp_bpl/029_image_chat_live_layer_29.png",
          "x": 1423.2,
          "y": 199.44,
          "width": 468,
          "height": 563
        },
        {
          "kind": "image",
          "id": "image_chat_live_layer_layer_30",
          "src": "assets/layers/sp_bpl/030_image_chat_live_layer_layer_30.png",
          "x": 1690.56,
          "y": 184.56,
          "width": 229,
          "height": 232
        },
        {
          "kind": "image",
          "id": "image_chat_live_layer_layer_31",
          "src": "assets/layers/sp_bpl/031_image_chat_live_layer_layer_31.png",
          "x": 1386.48,
          "y": 546.72,
          "width": 201,
          "height": 246
        },
        {
          "kind": "text",
          "id": "chat_title",
          "default": "CHAT",
          "x": 1425.84,
          "y": 161.04,
          "width": 121.44,
          "height": 29.76,
          "fontSize": 9.498,
          "fontFamily": "FZCCHJW",
          "fontFallback": "Arial",
          "fontWeight": 400,
          "color": "#ffeeff",
          "horizontalScale": 1.0,
          "textAlign": "left",
          "verticalAlign": "center"
        },
        {
          "kind": "image",
          "id": "image_advertisement_tpls3logo_33",
          "src": "assets/layers/sp_bpl/033_image_advertisement_tpls3logo_33.png",
          "x": 1420.08,
          "y": 24.0,
          "width": 181,
          "height": 101
        },
        {
          "kind": "image",
          "id": "image_advertisement_33logo_34",
          "src": "assets/layers/sp_bpl/034_image_advertisement_33logo_34.png",
          "x": 1625.52,
          "y": 32.64,
          "width": 270,
          "height": 78
        }
      ]
    },
    "live": {
      "layers": [
        {
          "kind": "image",
          "id": "image_background_color_0",
          "src": "assets/layers/live/000_image_background_color_0.png",
          "x": 0.0,
          "y": 0.0,
          "width": 1920,
          "height": 1080
        },
        {
          "kind": "image",
          "id": "image_layer_layer_1",
          "src": "assets/layers/live/001_image_layer_layer_1.png",
          "x": 142.8,
          "y": 914.16,
          "width": 938,
          "height": 108
        },
        {
          "kind": "image",
          "id": "image_layer_tpls3logo_2",
          "src": "assets/layers/live/002_image_layer_tpls3logo_2.png",
          "x": 1273.92,
          "y": 870.96,
          "width": 175,
          "height": 97
        },
        {
          "kind": "image",
          "id": "image_layer_33logo_3",
          "src": "assets/layers/live/003_image_layer_33logo_3.png",
          "x": 1231.92,
          "y": 984.96,
          "width": 259,
          "height": 75
        },
        {
          "kind": "image",
          "id": "image_layer_layer_4",
          "src": "assets/layers/live/004_image_layer_layer_4.png",
          "x": 54.96,
          "y": 864.96,
          "width": 177,
          "height": 205
        },
        {
          "kind": "image",
          "id": "image_layer_layer_5",
          "src": "assets/layers/live/005_image_layer_layer_5.png",
          "x": 973.92,
          "y": 864.96,
          "width": 200,
          "height": 205
        },
        {
          "kind": "image",
          "id": "image_layer_6",
          "src": "assets/layers/live/006_image_layer_6.png",
          "x": 30.96,
          "y": 38.88,
          "width": 1449,
          "height": 815
        },
        {
          "kind": "image",
          "id": "image_chat_layer_7",
          "src": "assets/layers/live/007_image_chat_layer_7.png",
          "x": 1508.16,
          "y": 38.64,
          "width": 391,
          "height": 1022
        },
        {
          "kind": "image",
          "id": "image_chat_layer_8",
          "src": "assets/layers/live/008_image_chat_layer_8.png",
          "x": 1518.0,
          "y": 85.92,
          "width": 372,
          "height": 965
        },
        {
          "kind": "image",
          "id": "image_chat_layer_image_9",
          "src": "assets/layers/live/009_image_chat_layer_image_9.png",
          "x": 1689.6,
          "y": 71.04,
          "width": 230,
          "height": 232
        },
        {
          "kind": "image",
          "id": "image_chat_layer_image_10",
          "src": "assets/layers/live/010_image_chat_layer_image_10.png",
          "x": 1481.52,
          "y": 835.92,
          "width": 201,
          "height": 244
        },
        {
          "kind": "text",
          "id": "chat_title",
          "default": "CHAT",
          "x": 1520.64,
          "y": 47.76,
          "width": 121.2,
          "height": 29.76,
          "fontSize": 9.486,
          "fontFamily": "FZCCHJW",
          "fontFallback": "Arial",
          "fontWeight": 400,
          "color": "#ffeeff",
          "horizontalScale": 1.0,
          "textAlign": "left",
          "verticalAlign": "center"
        }
      ]
    }
  }
};
